from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget



class Window(QtWidgets.QMainWindow):
    def __init__(self, parent = None):

        QtWidgets.QMainWindow.__init__(self,parent)
        self.setupui(self)

    def setupui(self, mainwindow):
        mainwindow.setObjectName("MainWindow")
        mainwindow.resize(842, 645)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.HomeTab = QtWidgets.QWidget()
        self.HomeTab.setObjectName("HomeTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.HomeTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.HomeTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.HomeTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.HomeTab)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_2.addWidget(self.plainTextEdit_2, 1, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.HomeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(369, 0))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 1, 1, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.HomeTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.HomeTab)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout_2.addWidget(self.plainTextEdit_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.HomeTab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.HomeTab)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_2.addWidget(self.plainTextEdit_3, 3, 1, 1, 5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.HomeTab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.HomeTab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.HomeTab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 3, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.HomeTab)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_3.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.HomeTab)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.HomeTab)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 4, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.HomeTab)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 1, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.HomeTab)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.HomeTab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.HomeTab)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 4, 0, 1, 5)
        self.pushButton = QtWidgets.QPushButton(self.HomeTab)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 4, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.HomeTab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 5, 0, 1, 6)
        self.tabWidget.addTab(self.HomeTab, "")
        self.LauncherTab = QtWidgets.QWidget()
        self.LauncherTab.setObjectName("LauncherTab")
        self.groupBox = QtWidgets.QGroupBox(self.LauncherTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 351, 101))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 70, 201, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.LauncherTab)
        self.groupBox_5.setGeometry(QtCore.QRect(382, 0, 421, 261))
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_7.setGeometry(QtCore.QRect(40, 20, 70, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_8.setGeometry(QtCore.QRect(40, 50, 70, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_9.setGeometry(QtCore.QRect(40, 80, 70, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_7.raise_()
        self.checkBox_8.raise_()
        self.checkBox_9.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.LauncherTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 351, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(0, 20, 151, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 60, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 60, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 90, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 90, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(190, 20, 141, 131))
        self.textEdit.setObjectName("textEdit")
        self.groupBox_5.raise_()
        self.comboBox_5.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.textEdit.raise_()
        self.groupBox_3 = QtWidgets.QGroupBox(self.LauncherTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 351, 281))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_6.setGeometry(QtCore.QRect(90, 20, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_7.setGeometry(QtCore.QRect(90, 60, 69, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_8.setGeometry(QtCore.QRect(90, 100, 69, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(0, "")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_9.setGeometry(QtCore.QRect(90, 140, 69, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.setItemText(0, "")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_10.setGeometry(QtCore.QRect(90, 180, 69, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.setItemText(0, "")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(200, 30, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(200, 50, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setGeometry(QtCore.QRect(200, 70, 70, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_6.setGeometry(QtCore.QRect(200, 90, 70, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 71, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(16, 100, 61, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(26, 140, 51, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(50, 180, 31, 16))
        self.label_13.setObjectName("label_13")
        self.groupBox_4 = QtWidgets.QGroupBox(self.LauncherTab)
        self.groupBox_4.setGeometry(QtCore.QRect(380, 270, 421, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tabWidget.addTab(self.LauncherTab, "")
        self.ProfileTab = QtWidgets.QWidget()
        self.ProfileTab.setObjectName("ProfileTab")
        self.groupBox_10 = QtWidgets.QGroupBox(self.ProfileTab)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 351, 101))
        self.groupBox_10.setObjectName("groupBox_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 70, 201, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_15.setGeometry(QtCore.QRect(270, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.groupBox_11 = QtWidgets.QGroupBox(self.ProfileTab)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 120, 351, 161))
        self.groupBox_11.setObjectName("groupBox_11")
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_11.setGeometry(QtCore.QRect(0, 20, 151, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 60, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_17.setGeometry(QtCore.QRect(80, 60, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 90, 75, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_19.setGeometry(QtCore.QRect(80, 90, 75, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_11)
        self.textEdit_4.setGeometry(QtCore.QRect(190, 20, 141, 131))
        self.textEdit_4.setObjectName("textEdit_4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.ProfileTab)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 290, 161, 261))
        self.groupBox_12.setObjectName("groupBox_12")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_22.setGeometry(QtCore.QRect(60, 230, 91, 21))
        self.pushButton_22.setObjectName("pushButton_22")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_12)
        self.listWidget_3.setEnabled(False)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 50, 141, 171))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 20, 113, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.groupBox_13 = QtWidgets.QGroupBox(self.ProfileTab)
        self.groupBox_13.setGeometry(QtCore.QRect(180, 290, 181, 261))
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_20.setGeometry(QtCore.QRect(50, 10, 61, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_21.setGeometry(QtCore.QRect(110, 10, 71, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_13)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 40, 171, 211))
        self.listWidget_2.setObjectName("listWidget_2")
        self.groupBox_14 = QtWidgets.QGroupBox(self.ProfileTab)
        self.groupBox_14.setGeometry(QtCore.QRect(370, 10, 441, 541))
        self.groupBox_14.setObjectName("groupBox_14")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_14)
        self.treeWidget.setGeometry(QtCore.QRect(10, 30, 421, 501))
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        self.treeWidget.header().setVisible(False)
        self.tabWidget.addTab(self.ProfileTab, "")
        self.ContentTab = QtWidgets.QWidget()
        self.ContentTab.setObjectName("ContentTab")
        self.groupBox_6 = QtWidgets.QGroupBox(self.ContentTab)
        self.groupBox_6.setGeometry(QtCore.QRect(9, 0, 391, 551))
        self.groupBox_6.setObjectName("groupBox_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_2.setGeometry(QtCore.QRect(13, 20, 361, 521))
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.ContentTab)
        self.groupBox_7.setGeometry(QtCore.QRect(420, 0, 391, 551))
        self.groupBox_7.setObjectName("groupBox_7")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit_3.setGeometry(QtCore.QRect(13, 20, 361, 521))
        self.textEdit_3.setObjectName("textEdit_3")
        self.tabWidget.addTab(self.ContentTab, "")
        self.ServerTab = QtWidgets.QWidget()
        self.ServerTab.setObjectName("ServerTab")
        self.groupBox_8 = QtWidgets.QGroupBox(self.ServerTab)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 10, 811, 301))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 10, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_9.setGeometry(QtCore.QRect(730, 10, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_10.setGeometry(QtCore.QRect(564, 270, 121, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_11.setGeometry(QtCore.QRect(700, 270, 91, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_4.setGeometry(QtCore.QRect(472, 10, 251, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_8)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 791, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.groupBox_9 = QtWidgets.QGroupBox(self.ServerTab)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 309, 811, 251))
        self.groupBox_9.setObjectName("groupBox_9")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_12.setGeometry(QtCore.QRect(610, 220, 111, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_13.setGeometry(QtCore.QRect(530, 220, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_14.setGeometry(QtCore.QRect(730, 220, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_9)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 781, 61))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_9)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 100, 791, 111))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.ServerTab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.actionCreate_Desktop_Icon = QtWidgets.QAction(mainwindow)
        self.actionCreate_Desktop_Icon.setPriority(QtWidgets.QAction.HighPriority)
        self.actionCreate_Desktop_Icon.setObjectName("actionCreate_Desktop_Icon")
        self.actionImport = QtWidgets.QAction(mainwindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(mainwindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(mainwindow)
        self.actionExit.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(mainwindow)
        self.actionSettings.setPriority(QtWidgets.QAction.HighPriority)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAdv_Profile_Manager = QtWidgets.QAction(mainwindow)
        self.actionAdv_Profile_Manager.setObjectName("actionAdv_Profile_Manager")
        self.actionContent_Manager = QtWidgets.QAction(mainwindow)
        self.actionContent_Manager.setObjectName("actionContent_Manager")
        self.actionServer_Manager_Client = QtWidgets.QAction(mainwindow)
        self.actionServer_Manager_Client.setObjectName("actionServer_Manager_Client")
        self.actionCheck_For_Updates = QtWidgets.QAction(mainwindow)
        self.actionCheck_For_Updates.setObjectName("actionCheck_For_Updates")
        self.actionAbout = QtWidgets.QAction(mainwindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSetup_Debug = QtWidgets.QAction(mainwindow)
        self.actionSetup_Debug.setObjectName("actionSetup_Debug")
        self.menuFile.addAction(self.actionCreate_Desktop_Icon)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuEdit.addAction(self.actionAdv_Profile_Manager)
        self.menuTools.addAction(self.actionContent_Manager)
        self.menuTools.addAction(self.actionServer_Manager_Client)
        self.menuHelp.addAction(self.actionCheck_For_Updates)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionSetup_Debug)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainwindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle("MainWindow")
        self.label_3.setText("Addon News")
        self.label_4.setText("Clan News")
        self.label_2.setText("Official Dev Chatter")
        self.label.setText("Official Arma News")
        self.label_5.setText("Addon Profile")
        self.label_6.setText("Launch Profile")
        self.checkBox.setText("Debug (No Launch)")
        self.checkBox_2.setText("Join Server on Startup")
        self.label_7.setText("Player Profile")
        self.label_8.setText("Multiplayer Profile")
        self.pushButton.setText("Deploy")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HomeTab), "Home")
        self.groupBox.setTitle("Launch Profile")
        self.lineEdit_2.setAccessibleName("ProfileName")
        self.lineEdit_2.setAccessibleDescription("ProfileName")
        self.lineEdit_2.setText("Profile Name")
        self.lineEdit_3.setText("Profile Description")
        self.pushButton_2.setText("Create New")
        self.groupBox_5.setTitle("Preferences")
        self.checkBox_7.setText("CheckBox")
        self.checkBox_8.setText("CheckBox")
        self.checkBox_9.setText("CheckBox")
        self.groupBox_2.setTitle("Edit Launch Profiles")
        self.comboBox_5.setItemText(0, "Profile Name")
        self.comboBox_5.setItemText(1, "Default")
        self.pushButton_3.setText("Save")
        self.pushButton_4.setText("Load")
        self.pushButton_5.setText("Duplicate")
        self.pushButton_6.setText("Delete")
        self.groupBox_3.setTitle("Performance")
        self.comboBox_6.setItemText(1, "1")
        self.comboBox_6.setItemText(2, "2")
        self.comboBox_6.setItemText(3, "3")
        self.comboBox_6.setItemText(4, "4")
        self.comboBox_6.setItemText(5, "5")
        self.comboBox_6.setItemText(6, "6")
        self.comboBox_7.setItemText(1, "0")
        self.comboBox_7.setItemText(2, "1")
        self.comboBox_7.setItemText(3, "3")
        self.comboBox_7.setItemText(4, "5")
        self.comboBox_7.setItemText(5, "7")
        self.comboBox_8.setItemText(1, "256")
        self.comboBox_8.setItemText(2, "512")
        self.comboBox_8.setItemText(3, "1024")
        self.comboBox_8.setItemText(4, "2047")
        self.comboBox_9.setItemText(1, "128")
        self.comboBox_9.setItemText(2, "256")
        self.comboBox_9.setItemText(3, "512")
        self.comboBox_9.setItemText(4, "1024")
        self.comboBox_9.setItemText(5, "2047")
        self.comboBox_10.setItemText(1, "Empty")
        self.comboBox_10.setItemText(2, "Stratis")
        self.comboBox_10.setItemText(3, "Altis")
        self.checkBox_3.setText("High Value Process")
        self.checkBox_4.setText("No Splash")
        self.checkBox_5.setText("Skip Intro")
        self.checkBox_6.setText("No Logs")
        self.label_9.setText("CPU Count")
        self.label_10.setText("Extra Threads")
        self.label_11.setText("Max Memory")
        self.label_12.setText("Max VRAM")
        self.label_13.setText("World")
        self.groupBox_4.setTitle("GroupBox")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LauncherTab), "Game Launcher")
        self.groupBox_10.setTitle("Addon Profile")
        self.lineEdit_5.setAccessibleName( "ProfileName")
        self.lineEdit_5.setAccessibleDescription("ProfileName")
        self.lineEdit_5.setText("Profile Name")
        self.lineEdit_6.setText("Profile Description")
        self.pushButton_15.setText("Create New")
        self.groupBox_11.setTitle("Edit Addon Profiles")
        self.comboBox_11.setItemText(0, "Profile Name")
        self.comboBox_11.setItemText(1, "Default")
        self.pushButton_16.setText("Save")
        self.pushButton_17.setText("Load")
        self.pushButton_18.setText("Duplicate")
        self.pushButton_19.setText("Delete")
        self.groupBox_12.setTitle("Clan Required Addons")
        self.pushButton_22.setText("Add All Required")
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText("CBA A3")
        item = self.listWidget_3.item(1)
        item.setText("ACE 3")
        item = self.listWidget_3.item(2)
        item.setText("ACRE 3")
        item = self.listWidget_3.item(3)
        item.setText("Gary\'s M4 Pack")
        item = self.listWidget_3.item(4)
        item.setText("Johnny\'s Chemlight Mod")
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.lineEdit_7.setText("ViperNet Gaming")
        self.groupBox_13.setTitle("Addon Order")
        self.pushButton_20.setText("Move Up")
        self.pushButton_21.setText("Move Down")
        self.groupBox_14.setTitle("Select Installed Addons")
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, "Advanced Combat Environment 3")
        self.treeWidget.topLevelItem(0).child(0).setText(0, "ACE 3 Core")
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, "v1.1")
        self.treeWidget.topLevelItem(1).setText(0, "Advanced Combat Radio Environment 3")
        self.treeWidget.topLevelItem(1).child(0).setText(0, "ACRE 3")
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, "v1.0")
        self.treeWidget.topLevelItem(2).setText(0, "Community Base Addons 3")
        self.treeWidget.topLevelItem(2).child(0).setText(0,  "CBA_A3")
        self.treeWidget.topLevelItem(2).child(0).child(0).setText(0,  "v0.3")
        self.treeWidget.topLevelItem(3).setText(0,  "Gary\'s M4 Pack")
        self.treeWidget.topLevelItem(3).child(0).setText(0,  "GAR M4")
        self.treeWidget.topLevelItem(3).child(0).child(0).setText(0,  "v10.2")
        self.treeWidget.topLevelItem(4).setText(0,  "Jesus\'s Reminton 870 Pack")
        self.treeWidget.topLevelItem(4).child(0).setText(0, "WWJD 870")
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ProfileTab),  "Addon Profiles")
        self.groupBox_6.setTitle("Available Addons")
        self.groupBox_7.setTitle("Installed Addons")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContentTab),  "Content Sync")
        self.groupBox_8.setTitle("Server Browser")
        self.pushButton_7.setText("Refresh")
        self.pushButton_8.setText("Search")
        self.pushButton_9.setText("Advanced...")
        self.pushButton_10.setText("View Server Details")
        self.pushButton_11.setText("Add to Favorites")
        self.lineEdit_4.setText("Server Search")
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText("Server Name")
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText("Type")
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText("Mission Name")
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText("New Column")
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText("Players")
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText("Ping")
        self.groupBox_9.setTitle("Favorite Servers")
        self.pushButton_12.setText("View Server Details")
        self.pushButton_13.setText("Add Custom")
        self.pushButton_14.setText("Remove")
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText("VNG Training Server")
        item = self.listWidget.item(1)
        item.setText("VNG Public Server")
        item = self.listWidget.item(2)
        item.setText("Joe\'s Server")
        self.listWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText("Server Name")
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText("Type")
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText("Mission Name")
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText("New Column")
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText("Players")
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText("Ping")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ServerTab),  "Server Browser")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6),  "Tab 6")
        self.menuFile.setTitle("File")
        self.menuEdit.setTitle("Edit")
        self.menuTools.setTitle("Tools")
        self.menuHelp.setTitle("Help")
        self.actionCreate_Desktop_Icon.setText("Create Desktop Icon")
        self.actionImport.setText("Import")
        self.actionExport.setText("Export")
        self.actionExit.setText("Exit")
        self.actionSettings.setText("Settings")
        self.actionAdv_Profile_Manager.setText("Adv. Profile Manager")
        self.actionContent_Manager.setText("Content Dev")
        self.actionServer_Manager_Client.setText("Server Manager Client")
        self.actionCheck_For_Updates.setText("Check For Updates")
        self.actionAbout.setText("About...")
        self.actionSetup_Debug.setText("Setup Debug")
